### ISSUE TITLE
Unhandled exception. System.TypeLoadException

### ISSUE THREAD

**Issue by Flaviusns** [gingemonster/GameBoyPngConverter#8]
Hello, I'm trying to use the tool but it don't work. The following error prompts:

`Unhandled exception. System.TypeLoadException
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromStream(IStream stream, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Stream stream, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(Stream stream)
   at GameBoyPngConverter.Program.Main(String[] args)
   at GameBoyPngConverter.Program.<Main>(String[] args)`
   
   Find attached the image I tested. 

**Important Info**

OS: Windows 11 22H2
Using Release V1 works perfectly, only happens with V2 release.

Thank you very much for the tool

![PruebaMario](https://user-images.githubusercontent.com/25839799/229363457-8c961128-1146-43f2-b8b3-d1d467a8c940.png)

**Comment by KittenPixel** [comment]
I have the same issue I am trying to use this image btw 
![Untitled-2](https://github.com/gingemonster/GameBoyPngConverter/assets/79544605/4b3fd166-c111-4037-a05c-0b625dd8a161)

**Comment by wirehack7** [comment]
Having the same.
I hope this repo is not dead

**Comment by lldohmann** [comment]
I'm having the same issue here too with this image. 
![Background](https://github.com/gingemonster/GameBoyPngConverter/assets/26883371/a93617c5-6fd5-4af0-9e01-425a3b7d2be7)
Same console output and all. At first I thought the image was too complicated but the other posts here show the same issue with less complicated images. 
<img width="766" alt="image" src="https://github.com/gingemonster/GameBoyPngConverter/assets/26883371/46302ef1-4a61-4bff-a94d-106285ebafbf">

**Comment by leonelsanchesdasilva** [comment]
cc @ItsMeSousuke @gingemonster 

I got to use version 1.0, having this error on version 2.0.

**Comment by ItsMeSousuke** [comment]
Thank you for the report.
I cannot reproduce this bug on my machine but I've created PR where I've removed dependency to System.Drawing which I hope helps you.

**Comment by DT153-hub** [comment]
@ItsMeSousuke any word on getting the fix for this merged?

**Comment by ItsMeSousuke** [comment]
@DT153-hub Unfortunately I have no idea, I've created a release 2.1 on my fork so please try it :)
https://github.com/ItsMeSousuke/GameBoyPngConverter/releases/tag/v2.1

FYI @leonelsanchesdasilva
